name: system_auth
description: "system authentification"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
 # flutter: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
#  firebase_core: ^2.3.0
  cupertino_icons: ^1.0.6
#  firebase_auth: ^4.19.5
#  cloud_firestore: ^4.17.3
  leak_tracker: ^10.0.4
  material_color_utilities: ^0.8.0
  meta: ^1.12.0
  lottie: ^1.2.0
  http: ^1.2.1
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  leak_tracker_flutter_testing: ^3.0.3
  lints: ^3.0.0
  test_api: 0.7.0  # Aligned with flutter_test constraint
  vm_service: 14.2.1  # Aligned with flutter_test constraint
  loading_animation_widget: ^1.2.1

flutter:
  uses-material-design: true


  # Uncomment and add assets if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment and add fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
